//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IPVL {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class IPVLResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal IPVLResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IPVL.IPVLResource", typeof(IPVLResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to { &quot;.xls&quot;, &quot;.pdf&quot;, &quot;.txt&quot;, &quot;.php&quot;, &quot;.gif&quot;, &quot;.tif&quot;, &quot;.bmp&quot; }.
        /// </summary>
        internal static string VALID_FILE_EXTENSIONS {
            get {
                return ResourceManager.GetString("VALID_FILE_EXTENSIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D0-CF-11-E0-A1-B1-1A-E1.
        /// </summary>
        internal static string VALID_FILE_EXTENSIONS_DOC {
            get {
                return ResourceManager.GetString("VALID_FILE_EXTENSIONS_DOC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 25-50-44-46.
        /// </summary>
        internal static string VALID_FILE_EXTENSIONS_PDF {
            get {
                return ResourceManager.GetString("VALID_FILE_EXTENSIONS_PDF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 00-00-00-00-00-00-00-00-00-00.
        /// </summary>
        internal static string VALID_FILE_EXTENSIONS_TXT {
            get {
                return ResourceManager.GetString("VALID_FILE_EXTENSIONS_TXT", resourceCulture);
            }
        }
    }
}
